apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer-service
  labels:
    app: trainer-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trainer-service
  template:
    metadata:
      labels:
        app: trainer-service
    spec:
      containers:
        - name: trainer-service
          image: trainer-service:dev
          ports:
          - containerPort: 35678
          env:
          - name: PORT
            value: "35678"